### PR TITLE
Added ability to make shorter when calls

### PR DESCRIPTION
**Pull request by beaulm**
@casecode, @JBBryan, @glyyynn, @mona87, @tomhanlon - What do y'all think? This mod allows you to call When with a jQuery method to run on the selected element when it's found. For example: 

`when($('.this-div'), ['css', ['display', 'none']]);`

Which will run

`$('.this-div').css('display', 'none');`

When '.this-div' is found.

We could use an object instead of an array, though I'm not sure why we would if the goal is to simplify short When calls.

### CODE REVIEW

**Comment by tomfuertes** [comment]
Love the when PR! For some reason I still get those emails. What about detecting if second arg is a string and then using optional additional args after that. Aka

`when('.foo', 'css', 'display', 'none')`

-Tom (mobile) | 512.913.1086
https://www.linkedin.com/in/tomfuertes

**Comment by tomfuertes** [comment]
Love the when PR! What about detecting if second arg is a string and then using optional additional args after that. Aka

`when('#foo', 'css', 'display', 'none'); // => $('#foo').css('display','none');`

**Comment by beaulm** [comment]
The only problem I see with that @tomfuertes is the other optional parameters.

Speaking of which: @JBBryan ~ What's the difference between `optTimeout` and `optQuitPolling` in the call?

**Comment by tomhanlon** [comment]
In that case, we could/should consider passing the args as an object as Austin's very own Rebecca Murphy suggests: http://rmurphey.com/blog/2011/04/25/objects-as-arguments

**Comment by tomfuertes** [comment]
You can still grab the arguments optionally splicing arguments

```js
function when(arg1,arg2 /*optAdditionalArgs*/) {
  if (typeof arg === 'string'){
    var optionalArgs = [].splice(arguments, 2);
    // if ($(arg1).length) {
      $.fn.[arg2].apply($(arg1), optionalArgs);
    // }
  }
}
```

On Mon, Feb 1, 2016 at 1:35 PM, Tom Hanlon <notifications@github.com> wrote:

> In that case, we could/should consider passing the args as an object as
> Austin's very own Rebecca Murphy suggests:
> http://rmurphey.com/blog/2011/04/25/objects-as-arguments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clearhead/clearhead/pull/41#issuecomment-178144789>.
>



-- 
Tom Fuertes | (512) 913-1086
http://www.linkedin.com/in/tomfuertes

**Comment by beaulm** [comment]
That would work well with another When upgrade I'm thinking about: https://github.com/clearhead/clearhead/blob/efficient-when/src/when.js

The "efficient when" will start one loop to check for elements when initially called, then just use that same loop to check for elements until it's found everything, instead of starting a new loop for each element. The only downside to that approach that I can think of is that then you can't set `optTimeout` or `optQuitPolling` for each element. To solve that, I've added the ability to stop the When loop by calling `when('stop');` which you could do in a timeout or whenever you want.

One thing we have to consider is that if we change the list of parameters that When accepts, it will break old code if we rebuild it with the new module.

**Pull request closed without merging**
